name = "Cafeteria"
author = "Felipe Malicheski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e703908110b2301869bbf029f74550225aa7352529626f14c88bbd56234015"

[versions]
fabric = "0.16.2"
minecraft = "1.19"
