name = "Cafeteria"
author = "Felipe Malicheski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f6823bd6e026ba3e2cd108896fd9a638f93d6fbfb04c96ba2855991d8640280"

[versions]
fabric = "0.16.2"
minecraft = "1.19"
